### ISSUE TITLE
No support for writing bitarrays?

### ISSUE THREAD

**Issue by pTinosq** [koesie10/fsuipc-node#10]
When doing:
```js
obj.write(0x0B6B, fsuipc.Type.BitArray, 1, 1);
```

I noticed that it returns an error:
```js
TypeError: FSUIPC.Write: unsupported type for write
```

Am I writing bitarrays incorrectly or is this something that's been overlooked?

Apologies for all the issues, I'm just trying to make my way around the new writing system :)

**Comment by koesie10** [comment]
There's indeed no proper support for the `BitArray` type when writing a value since I wasn't entirely sure what the API should look like. However, you can still write to bit array fields by using one of the other types with the correct size. For `0x0B6B` you can just use `Type.Byte` since it's a value of 1 byte and manually write the correct bit values. Another option would be to use `Type.ByteArray` with a size of `1` and an array buffer of size 1 with exactly the same value, so it's easier to use the first option.

Your snippet would then probably be:

```js
obj.write(0x0B6B, fsuipc.Type.Byte, 1);
```

**Comment by pTinosq** [comment]
I'll be sure to try out your suggestions and use those for now. As for the API, having used the c# DLL before, the method used involved something similar to this layout:

Engine_offset[0] = true
Engine_offset[2]=true

(For failing engine 1 & 3)

Not sure if that helps at all :)

**Comment by pTinosq** [comment]
Just found a roadblock with the `fsuipc.Type.Byte, 1);` method. You can't get multiple engine failure since once you write byte 1, if you were to write byte 2, engine one will come back alive.

**Comment by davwheat** [comment]
That's intended.

You should write `0b00000001` for engine 1, `0b00000010` for 2, `0b00000011` for 1 and 2, etc.

They're a byte, meaning they're represented by 8 bits.

**Comment by pTinosq** [comment]
Ah I see, that makes a lot more sense now. Thanks!
