### ISSUE TITLE
Checking if obj is already open?

### ISSUE THREAD

**Issue by pTinosq** [koesie10/fsuipc-node#12]
I've got a looping script that loops every 100ms which seems to be too fast for fsuipc the module to close the obj. Is there any way to check if obj is open and to just skip the code if it is?

**Comment by koesie10** [comment]
I would recommend just keeping the object open, since establishing and closing the connection is quite slow and you can just re-use the object as long as it is open. You can use the `add` and `remove` methods to add/remove offsets between the calls.

Alternatively, if you do really need it to open and close on every invocation, you can use the fact that the `close` method also returns a promise, so you can keep track of whether the object is open yourself, using something like this:
```js
let isOpen = false;

setInterval(() => {
    obj.open()
        .then(() => {
            isOpen = true;
            
            // Add objects

            return obj.process();
        })
        .then(() => {
            return obj.close();
        })
        .catch(() => {
            return obj.close();
        })
        .finally(() => {
            isOpen = false;
        })
}, 100);
```
