### ISSUE TITLE
how to get simulator events?

### ISSUE THREAD

**Issue by Enrico1108** [koesie10/fsuipc-node#16]
Hello I would like to know how to get the simulator events with this lib

**Comment by westlakem** [comment]
Hello,

You need to understand the interactions with FSUPIC and how their buffer / offset system works.  I know you asked months ago, but I just came across this package that does a lot for you.  https://www.npmjs.com/package/@fsuipc/api  Hope that helps.

**Comment by koesie10** [comment]
I'm closing this issue since this is not natively supported by FSUIPC. Simulator events can only be received when using SimConnect. For checking data with FSUIPC, you would need to poll the offsets you want updates on as far as I know. The package linked by @westlakem seems to implement that exact behavior using this library.
