### ISSUE TITLE
ReadLVar is possible?

### ISSUE THREAD

**Issue by MMontalto** [koesie10/fsuipc-node#21]
Hi, I'm not an expert, but I'm trying to interface with some 3rd party Sim plugins. Unfortunately looking on the internet I found that it is necessary to read the LVAR, but to do so it's necessary at the moment a wasm module. I saw that FSUIPC has one already built into the installation.
I have not found any info about it in this repo, is it already implemented or is it possible to implant the reading of the local variables in the future? Thanks in advance!

**Comment by koesie10** [comment]
This is not something that's currently supported by this package since the WASM module uses a completely different method of communicating with the simulator. The WASM API actually uses SimConnect under the hood, rather than Windows pipes as used by FSUIPC. As such, a WASM interface for Node.js would best be provided by a separate package, based on https://github.com/jldowson/FSUIPC_WAPI.

I might have a go at implementing it this weekend, but I'm not completely sure how feasible it is.

**Comment by MMontalto** [comment]
Ok understood, thank you so much for the answer. Unfortunately I don't have the knowledge to do it, otherwise I would have tried to help you. If you can do it naturally if you find some time available, that would be a nice help/update included in the package!
Thanks again,
Take care!

**Comment by koesie10** [comment]
@MMontalto I have created a basic [`fsuipc-wasm`](https://github.com/koesie10/fsuipc-node/tree/main/packages/fsuipc-wasm) package which is a wrapper around the WASM interface provided by FSUIPC. It's also available on [npm](https://npmjs.org/package/fsuipc-wasm). There is no documentation for it, but [the types](https://github.com/koesie10/fsuipc-node/blob/main/packages/fsuipc-wasm/index.d.ts) should give you an idea for what is possible, and it's also close to [the C++ interface](https://github.com/jldowson/FSUIPC_WAPI/tree/master) so that might also be of some help.

**Comment by MMontalto** [comment]
Great, thank you very much!
