### ISSUE TITLE
add support for offset write

### ISSUE THREAD

**Issue by blackholegalaxy** [koesie10/fsuipc-node#5]
Hi @koesie10, do you intend to add support for Write offset values. It would be useful to be able to edit to be able to use fsuipc both ways.

**Comment by pTinosq** [comment]
Hello @blackholegalaxy @koesie10 has there been any update on this? I hadn't realised that this module doesn't feature offset writing until after I had set up my UI & Backend so I'm absolutely gutted to find out it doesn't. Has anyone made a forked version with offset writing enabled? FSUIPC backend isn't my area of expertise so I'm really not sure what to do anymore...

**Comment by koesie10** [comment]
Sorry about this neglicting this issue. I've just added write support, see https://github.com/koesie10/fsuipc-node/blob/master/test/write.js for an example. I've not tested it thoroughly, but writing numbers to offsets should work. I'm not too sure whether writing to strings or byte arrays works, since there are not too many offsets that actually require that.

**Comment by pTinosq** [comment]
You're an absolute legend and have my utmost respect for coming back to an abandoned project just to help out some random developer. We need more developers like you in this world ❤

**Comment by blackholegalaxy** [comment]
That's pretty neat indeed. I'll add write support in my offset library

**Comment by pTinosq** [comment]
@blackholegalaxy Not sure if this is the best place to discuss this but you can shoot me a friend request on discord of you want pTinosq#6490
